Add script to update to currently supported Python versions.
zopefoundation/meta pull request #255
Opened 2024-06-14 06:46 UTC by icemac

Remove previous script to drop support for old Python versions instead.

The script is now able to drop and add in one go and does not need to be adapted for version updates in the range of supported versions.

See https://github.com/zopefoundation/z3c.currency/pull/8 which was built using this PR.

2024-06-14 06:54 UTC, dataflake requested changes

2024-06-14 06:54 UTC, dataflake commented on config/README.rst
> +It supports a parameter ``--interactive`` to not automatically commiting the
```suggestion
It supports a parameter ``--interactive`` to not automatically commit the
```

2024-06-14 06:54 UTC, dataflake commented on config/README.rst
> +It supports a parameter ``--interactive`` to not automatically commiting the
I'd really like an alternate spelling `--no-commit` for this flag so it is the same as for the main configure script, some way to make all changes but not do a `git commit`.

2024-06-14 15:12 UTC, dataflake commented
The ``--no-commit`` flag is not all that different from ``--interactive`` because those zest.releaser scripts don't have a simple "don't commit" mode, they either commit everything without input or ask questions and then ask about a commit, which is annoying.

2024-06-14 15:13 UTC, dataflake commented
Tested with https://github.com/zopefoundation/MultiMapping/pull/9

2024-06-14 16:05 UTC, icemac commented
@dataflake I like the changes you made, so I enabled auto-merge which will fire when you will approve this PR.

2024-06-15 07:23 UTC, dataflake approved these changes

2024-06-15 07:23 UTC, merged